### ISSUE TITLE
Allow users to see their own favourites

### ISSUE THREAD

**Issue by benrmatthews** [goodhere/goodhere#11]
We can create a page like /account/favourites that allows an authenticated user to view their own favorites. It will allow us to  provide incremental value on top of our MVP favourites functionality.

The UI can be roughly based on the the Lists design, though using our existing components.

- The title would just be something  like "Your Favorites"
- The list items would use the existing OrganizationCard design
- Everything else in the mock can be left out (karma, profile info, description, discussions, "also in...")

**Comment by MattMarquise** [comment]
This would be an important feature

**Comment by MattMarquise** [comment]
Any thoughts on how you'd like this to be done? I've worked on creating a feature exactly you're thinking about numerous times before, though mainly in Laravel.
